// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "ComingServer": account Resource Client
//
// Command:
// $ goagen
// --design=github.com/TinyKitten/ComingServer/design
// --out=$(GOPATH)/src/github.com/TinyKitten/ComingServer
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// UpdatePasswordAccountPayload is the account update password action payload.
type UpdatePasswordAccountPayload struct {
	// パスワード
	Password string `form:"password" json:"password" yaml:"password" xml:"password"`
}

// UpdatePasswordAccountPath computes a request path to the update password action of account.
func UpdatePasswordAccountPath() string {

	return fmt.Sprintf("/v1/account/password")
}

// アカウントのパスワードを更新
func (c *Client) UpdatePasswordAccount(ctx context.Context, path string, payload *UpdatePasswordAccountPayload, contentType string) (*http.Response, error) {
	req, err := c.NewUpdatePasswordAccountRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewUpdatePasswordAccountRequest create the request corresponding to the update password action endpoint of the account resource.
func (c *Client) NewUpdatePasswordAccountRequest(ctx context.Context, path string, payload *UpdatePasswordAccountPayload, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("PUT", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	if c.JWTSigner != nil {
		if err := c.JWTSigner.Sign(req); err != nil {
			return nil, err
		}
	}
	return req, nil
}
