// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "ComingServer": websocket Resource Client
//
// Command:
// $ goagen
// --design=github.com/TinyKitten/ComingServer/design
// --out=$(GOPATH)/src/github.com/TinyKitten/ComingServer
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"golang.org/x/net/websocket"
	"net/url"
	"strconv"
)

// ReceivePeerLocationWebsocketPath computes a request path to the receive peer location action of websocket.
func ReceivePeerLocationWebsocketPath() string {

	return fmt.Sprintf("/v1/pod")
}

// ポッドのWebSocketエンドポイント
func (c *Client) ReceivePeerLocationWebsocket(ctx context.Context, path string, token string) (*websocket.Conn, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "ws"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	values.Set("token", token)
	u.RawQuery = values.Encode()
	url_ := u.String()
	cfg, err := websocket.NewConfig(url_, url_)
	if err != nil {
		return nil, err
	}
	return websocket.DialConfig(cfg)
}

// SendCurrentPeerLocationWebsocketPath computes a request path to the send current peer location action of websocket.
func SendCurrentPeerLocationWebsocketPath() string {

	return fmt.Sprintf("/v1/peer")
}

// ピアのWebSocketエンドポイント
func (c *Client) SendCurrentPeerLocationWebsocket(ctx context.Context, path string, latitude float64, longitude float64, token string) (*websocket.Conn, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "ws"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	values := u.Query()
	tmp31 := strconv.FormatFloat(latitude, 'f', -1, 64)
	values.Set("latitude", tmp31)
	tmp32 := strconv.FormatFloat(longitude, 'f', -1, 64)
	values.Set("longitude", tmp32)
	values.Set("token", token)
	u.RawQuery = values.Encode()
	url_ := u.String()
	cfg, err := websocket.NewConfig(url_, url_)
	if err != nil {
		return nil, err
	}
	return websocket.DialConfig(cfg)
}
