version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/go/src/github.com/TinyKitten/ComingServer
    depends_on:
      - db
  db:
    image: mariadb:10.4.3
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: comingserver
      MYSQL_USER: comingserver
      MYSQL_PASSWORD: comingserver
    volumes:
        - ./data/mysql:/var/lib/mysql
  redis:
    image: redis:5.0.4-alpine
    command: redis-server --appendonly yes
    volumes:
      - ./data/redis:/data