version: "3"
volumes:
  db:
  redis:
services:
  app:
    build: .
    ports:
      - "52360:52360"
    volumes:
      - .:/go/src/github.com/TinyKitten/ComingServer
    depends_on:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      APPROACHED_THRESHOLD: 1000
      LEAVE_THRESHOLD: 1500
      DSN: comingserver:comingserver@tcp(db:3306)/comingserver?parseTime=true&loc=Asia%2FTokyo
    restart: always
  db:
    image: mysql:5.7.25
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: comingserver
      MYSQL_USER: comingserver
      MYSQL_PASSWORD: comingserver
    volumes:
        - db:/var/lib/mysql
        - ./migrations:/docker-entrypoint-initdb.d
    restart: always
  redis:
    image: redis:5.0.4-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    restart: always
