version: "3"
volumes:
  db:
  redis:
services:
  app:
    image: asia.gcr.io/coming/comingserver
    ports:
      - "52360:52360"
    links:
      - db
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      APPROACHED_THRESHOLD: 1000
      LEAVE_THRESHOLD: 1500
      DSN: comingserver:comingserver@tcp(db:3306)/comingserver?parseTime=true&loc=Asia%2FTokyo
    restart: always
  db:
    image: asia.gcr.io/coming/comingserver-mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: comingserver
      MYSQL_USER: comingserver
      MYSQL_PASSWORD: comingserver
    volumes:
        - db:/var/lib/mysql
    restart: always
  redis:
    image: redis:5.0.4-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    restart: always
