-- +migrate Up
-- SQL in section 'Up' is executed when this migration is applied
CREATE TABLE users
(
	id BIGINT unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
	screen_name VARCHAR(255) UNIQUE NOT NULL COMMENT 'スクリーンネーム',
	password VARCHAR(255) NOT NULL COMMENT 'パスワード',
    privilege_id BIGINT unsigned NOT NULL COMMENT 'ピアID',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '作成日',
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新日',
	PRIMARY KEY (id)
) COMMENT = 'ユーザー';

CREATE TABLE privileges
(
	id BIGINT unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
	code VARCHAR(255) UNIQUE NOT NULL COMMENT '権限コード',
	name VARCHAR(255) UNIQUE NOT NULL COMMENT '権限名',
	description VARCHAR(255) UNIQUE NOT NULL COMMENT '権限説明',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '作成日',
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新日',
	PRIMARY KEY (id)
) COMMENT = '権限';

CREATE TABLE pods
(
	id BIGINT unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
	code VARCHAR(255) UNIQUE NOT NULL COMMENT 'コード',
    latitude DOUBLE(8,6) NOT NULL COMMENT '緯度',
    longitude DOUBLE(9,6) NOT NULL COMMENT '緯度',
    approaching BOOLEAN DEFAULT FALSE COMMENT '装置にピアが接近している',
    token VARCHAR(255) NOT NULL COMMENT 'ポッドトークン',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '作成日',
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新日',
	PRIMARY KEY (id)
) COMMENT = 'ポッド';

CREATE TABLE peers
(
    id BIGINT unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
    code VARCHAR(255) UNIQUE NOT NULL COMMENT 'コード',
	token VARCHAR(255) NOT NULL COMMENT 'ピアトークン',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '作成日',
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新日',
	PRIMARY KEY (id)
) COMMENT = 'ピア';

CREATE TABLE peer_locations
(
    id BIGINT unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
    peer_id BIGINT unsigned NOT NULL COMMENT 'ピアID',
    latitude DOUBLE(8,6) NOT NULL COMMENT '緯度',
    longitude DOUBLE(9,6) NOT NULL COMMENT '緯度',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '作成日',
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新日',
	PRIMARY KEY (id)
) COMMENT = 'ピアの位置履歴';

CREATE TABLE peers_map
(
    id BIGINT unsigned NOT NULL AUTO_INCREMENT COMMENT 'ID',
    pod_id BIGINT unsigned NOT NULL COMMENT 'ポッドID',
    peer_id BIGINT unsigned UNIQUE NOT NULL COMMENT 'ピアID',
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '作成日',
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL COMMENT '更新日',
	PRIMARY KEY (id)
) COMMENT = 'どのどのピアがどのポッドに紐付いているか';

ALTER TABLE users
	ADD FOREIGN KEY (privilege_id)
	REFERENCES privileges (id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE peer_locations
	ADD FOREIGN KEY (peer_id)
	REFERENCES peers (id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE peers_map
	ADD FOREIGN KEY (pod_id)
	REFERENCES pods (id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

ALTER TABLE peers_map
	ADD FOREIGN KEY (peer_id)
	REFERENCES peers (id)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;

-- +migrate Down
-- SQL section 'Down' is executed when this migration is rolled back
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS privileges;
DROP TABLE IF EXISTS pods;
DROP TABLE IF EXISTS peers;
DROP TABLE IF EXISTS peer_locations;
DROP TABLE IF EXISTS peers_map;