// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "ComingServer": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/TinyKitten/ComingServer/design
// --out=$(GOPATH)/src/github.com/TinyKitten/ComingServer
// --version=v1.3.1

package app

import (
	"fmt"
	"strings"
)

// PeersHref returns the resource href.
func PeersHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/peers/%v", paramid)
}

// PodsHref returns the resource href.
func PodsHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/pods/%v", paramid)
}

// UsersHref returns the resource href.
func UsersHref(id interface{}) string {
	paramid := strings.TrimLeftFunc(fmt.Sprintf("%v", id), func(r rune) bool { return r == '/' })
	return fmt.Sprintf("/v1/users/%v", paramid)
}
