// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "ComingServer": swagger TestHelpers
//
// Command:
// $ goagen
// --design=github.com/TinyKitten/ComingServer/design
// --out=$(GOPATH)/src/github.com/TinyKitten/ComingServer
// --version=v1.3.1

package test
