// Package models contains the types for schema 'comingserver'.
package models

// Code generated by xo. DO NOT EDIT.

import (
	"errors"
	"time"
)

// Privilege represents a row from 'comingserver.privileges'.
type Privilege struct {
	ID          uint64    `json:"id"`          // id
	Code        string    `json:"code"`        // code
	Name        string    `json:"name"`        // name
	Description string    `json:"description"` // description
	CreatedAt   time.Time `json:"created_at"`  // created_at
	UpdatedAt   time.Time `json:"updated_at"`  // updated_at

	// xo fields
	_exists, _deleted bool
}

// Exists determines if the Privilege exists in the database.
func (p *Privilege) Exists() bool {
	return p._exists
}

// Deleted provides information if the Privilege has been deleted from the database.
func (p *Privilege) Deleted() bool {
	return p._deleted
}

// Insert inserts the Privilege to the database.
func (p *Privilege) Insert(db XODB) error {
	var err error

	// if already exist, bail
	if p._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO comingserver.privileges (` +
		`code, name, description, created_at, updated_at` +
		`) VALUES (` +
		`?, ?, ?, ?, ?` +
		`)`

	// run query
	XOLog(sqlstr, p.Code, p.Name, p.Description, p.CreatedAt, p.UpdatedAt)
	res, err := db.Exec(sqlstr, p.Code, p.Name, p.Description, p.CreatedAt, p.UpdatedAt)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// set primary key and existence
	p.ID = uint64(id)
	p._exists = true

	return nil
}

// Update updates the Privilege in the database.
func (p *Privilege) Update(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !p._exists {
		return errors.New("update failed: does not exist")
	}

	// if deleted, bail
	if p._deleted {
		return errors.New("update failed: marked for deletion")
	}

	// sql query
	const sqlstr = `UPDATE comingserver.privileges SET ` +
		`code = ?, name = ?, description = ?, created_at = ?, updated_at = ?` +
		` WHERE id = ?`

	// run query
	XOLog(sqlstr, p.Code, p.Name, p.Description, p.CreatedAt, p.UpdatedAt, p.ID)
	_, err = db.Exec(sqlstr, p.Code, p.Name, p.Description, p.CreatedAt, p.UpdatedAt, p.ID)
	return err
}

// Save saves the Privilege to the database.
func (p *Privilege) Save(db XODB) error {
	if p.Exists() {
		return p.Update(db)
	}

	return p.Insert(db)
}

// Delete deletes the Privilege from the database.
func (p *Privilege) Delete(db XODB) error {
	var err error

	// if doesn't exist, bail
	if !p._exists {
		return nil
	}

	// if deleted, bail
	if p._deleted {
		return nil
	}

	// sql query
	const sqlstr = `DELETE FROM comingserver.privileges WHERE id = ?`

	// run query
	XOLog(sqlstr, p.ID)
	_, err = db.Exec(sqlstr, p.ID)
	if err != nil {
		return err
	}

	// set deleted
	p._deleted = true

	return nil
}

// PrivilegeByCode retrieves a row from 'comingserver.privileges' as a Privilege.
//
// Generated from index 'code'.
func PrivilegeByCode(db XODB, code string) (*Privilege, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, code, name, description, created_at, updated_at ` +
		`FROM comingserver.privileges ` +
		`WHERE code = ?`

	// run query
	XOLog(sqlstr, code)
	p := Privilege{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, code).Scan(&p.ID, &p.Code, &p.Name, &p.Description, &p.CreatedAt, &p.UpdatedAt)
	if err != nil {
		return nil, err
	}

	return &p, nil
}

// PrivilegeByDescription retrieves a row from 'comingserver.privileges' as a Privilege.
//
// Generated from index 'description'.
func PrivilegeByDescription(db XODB, description string) (*Privilege, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, code, name, description, created_at, updated_at ` +
		`FROM comingserver.privileges ` +
		`WHERE description = ?`

	// run query
	XOLog(sqlstr, description)
	p := Privilege{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, description).Scan(&p.ID, &p.Code, &p.Name, &p.Description, &p.CreatedAt, &p.UpdatedAt)
	if err != nil {
		return nil, err
	}

	return &p, nil
}

// PrivilegeByName retrieves a row from 'comingserver.privileges' as a Privilege.
//
// Generated from index 'name'.
func PrivilegeByName(db XODB, name string) (*Privilege, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, code, name, description, created_at, updated_at ` +
		`FROM comingserver.privileges ` +
		`WHERE name = ?`

	// run query
	XOLog(sqlstr, name)
	p := Privilege{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, name).Scan(&p.ID, &p.Code, &p.Name, &p.Description, &p.CreatedAt, &p.UpdatedAt)
	if err != nil {
		return nil, err
	}

	return &p, nil
}

// PrivilegeByID retrieves a row from 'comingserver.privileges' as a Privilege.
//
// Generated from index 'privileges_id_pkey'.
func PrivilegeByID(db XODB, id uint64) (*Privilege, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`id, code, name, description, created_at, updated_at ` +
		`FROM comingserver.privileges ` +
		`WHERE id = ?`

	// run query
	XOLog(sqlstr, id)
	p := Privilege{
		_exists: true,
	}

	err = db.QueryRow(sqlstr, id).Scan(&p.ID, &p.Code, &p.Name, &p.Description, &p.CreatedAt, &p.UpdatedAt)
	if err != nil {
		return nil, err
	}

	return &p, nil
}
